'use client';
import {useMemo,useState} from 'react';
const styles=['Photorealistic','Vintage distressed','Bold vector','Watercolor','Retro 90s','3D illustration'];
const sizes=[['11 × 14 Adult',11,14],['12 × 16 Large',12,16],['10 × 12 Youth',10,12],['4 × 4 Left chest',4,4]] as const;
const WORKER='https://eky-ai-dtf-worker.chovez.workers.dev';

function fileToDataUrl(file:File){return new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=reject;r.readAsDataURL(file);});}

export default function Home(){
 const[p,setP]=useState(''); const[style,setStyle]=useState(styles[0]); const[size,setSize]=useState<(typeof sizes)[number]>(sizes[0]);
 const[busy,setBusy]=useState(false); const[msg,setMsg]=useState('Cloudflare AI is connected. Describe anything you want to create.'); const[image,setImage]=useState<string|null>(null);
 const[editImage,setEditImage]=useState<string|null>(null); const[editPrompt,setEditPrompt]=useState(''); const[editResult,setEditResult]=useState<string|null>(null); const[editBusy,setEditBusy]=useState(false); const[editMsg,setEditMsg]=useState('Upload an image and describe the change.');
 const optimized=useMemo(()=>p.trim()?`${p.trim()}. Style: ${style}. Professional DTF T-shirt artwork, isolated subject, transparent-style clean background, no shirt mockup, exact readable lettering, clean cutout edges, strong centered composition, print-safe detail.`:'',[p,style]);
 async function generate(){if(!optimized){setMsg('Type what you want first.');return}setBusy(true);setMsg('Generating with Cloudflare FLUX.1 Schnell…');try{const r=await fetch(`${WORKER}/generate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:optimized,steps:4})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Generation failed');setImage(`data:${d.image.mediaType};base64,${d.image.base64}`);setMsg('Image created with Cloudflare FLUX.1 Schnell.');}catch(e){setMsg(e instanceof Error?e.message:'Generation failed');}finally{setBusy(false)}}
 async function chooseEditImage(file?:File){if(!file)return;const data=await fileToDataUrl(file);setEditImage(data);setEditResult(null);setEditMsg('Image loaded. Describe exactly what you want changed.');}
 async function editUploaded(){if(!editImage){setEditMsg('Upload an image first.');return}if(!editPrompt.trim()){setEditMsg('Tell AI what you want changed.');return}setEditBusy(true);setEditMsg('Editing with Cloudflare image-to-image AI…');try{const r=await fetch(`${WORKER}/edit`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image:editImage,prompt:editPrompt.trim(),strength:0.72})});const text=await r.text();let d:any;try{d=JSON.parse(text)}catch{throw new Error(text||`Cloudflare edit failed (${r.status})`)}if(!r.ok)throw new Error(d.error||`Image edit failed (${r.status})`);const out=`data:${d.image.mediaType};base64,${d.image.base64}`;setEditResult(out);setImage(out);setEditMsg('✓ Edit complete. The changed image is shown beside the original.');setMsg('Image edit complete with Cloudflare AI.');}catch(e){setEditMsg(`Edit failed: ${e instanceof Error?e.message:'Unknown error'}`);}finally{setEditBusy(false)}}
 function updateApp(){const u=new URL(location.href);u.searchParams.set('update',Date.now().toString());location.replace(u.toString());}
 return <main className="app"><header><div><h1>EKY AI DTF Studio</h1><p>Cloudflare AI • DTF Creator & Editor</p></div><div className="topBtns"><button className="connected" onClick={()=>setMsg('Cloudflare Workers AI generation and image editing are connected.')}>✓ Cloudflare AI</button><button className="update" onClick={updateApp}>↻ Update</button></div></header>
 <section className="panel editPanel"><h2>Upload Image to Change</h2><p className="subtext">Choose a photo, logo, drawing, or design from your iPhone, then tell AI exactly what to change.</p><label className="uploadBox">Choose Image<input type="file" accept="image/*" onChange={e=>chooseEditImage(e.target.files?.[0])}/></label>{editImage&&<div className="editPreview"><div><b>Original</b><img src={editImage} alt="Uploaded image"/></div>{editResult&&<div><b>Edited</b><img src={editResult} alt="Edited image"/></div>}</div>}<textarea value={editPrompt} onChange={e=>setEditPrompt(e.target.value)} placeholder="Example: Change the hat to red, remove the background, add blue flames behind it, keep everything else the same…"/><div className="quickEdits"><button onClick={()=>setEditPrompt('Remove the background and replace it with a plain clean white background while preserving the subject and clean edges')}>Remove BG</button><button onClick={()=>setEditPrompt('Clean the edges, sharpen the artwork, reduce blur and preserve the original design for DTF printing')}>Clean Edges</button><button onClick={()=>setEditPrompt('Change only the colors I describe and preserve the original design, subject and composition')}>Change Colors</button></div><button className="primary" disabled={editBusy} onClick={editUploaded}>{editBusy?'Editing…':'✦ Change Uploaded Image'}</button><p className="status">{editMsg}</p>{editResult&&<a className="download" href={editResult} download="eky-dtf-edited.png">Download Edited PNG</a>}</section>
 <div className="layout"><section className="panel"><h2>Describe a New Design</h2><textarea value={p} onChange={e=>setP(e.target.value)} placeholder="Example: A whitetail buck coming through foggy Kentucky mountains, orange sunrise, bold KENTUCKY text..."/><div className="chips">{styles.map(s=><button key={s} className={style===s?'active':''} onClick={()=>setStyle(s)}>{s}</button>)}</div><label>DTF Size<select value={size[0]} onChange={e=>setSize(sizes.find(x=>x[0]===e.target.value)||sizes[0])}>{sizes.map(s=><option key={s[0]}>{s[0]}</option>)}</select></label><div className="promptBox"><b>AI optimized prompt</b><p>{optimized||'Your print-ready prompt will appear here.'}</p></div><button className="primary" disabled={busy} onClick={generate}>{busy?'Working…':'✦ Generate with Cloudflare FLUX'}</button><p className="status">{msg}</p></section><section className="panel"><h2>Creation</h2>{image?<><div className="checker"><img src={image} alt="Generated design"/></div><a className="download" href={image} download="eky-dtf-design.png">Download PNG</a></>:<div className="empty checker">Your AI artwork will appear here.</div>}<div className="stats"><span>{size[1]} × {size[2]} in</span><span>{size[1]*300} × {size[2]*300} px target</span><span>300 DPI target</span></div></section></div></main>}
